// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  Address,
  DataSourceTemplate,
  DataSourceContext
} from "@graphprotocol/graph-ts";

export class Loan extends DataSourceTemplate {
  static create(address: Address): void {
    DataSourceTemplate.create("Loan", [address.toHex()]);
  }

  static createWithContext(address: Address, context: DataSourceContext): void {
    DataSourceTemplate.createWithContext("Loan", [address.toHex()], context);
  }
}

export class ZKERC20 extends DataSourceTemplate {
  static create(address: Address): void {
    DataSourceTemplate.create("ZKERC20", [address.toHex()]);
  }

  static createWithContext(address: Address, context: DataSourceContext): void {
    DataSourceTemplate.createWithContext("ZKERC20", [address.toHex()], context);
  }
}
